```{r}
library(dplyr)
library(ggplot2)
library(car)
library(ggpubr)
library(tidyverse)
library(rstatix)
library(ggstatsplot)

setwd("C:/Users/Laura/Documents/code/MA-541")
df <- read.csv("Crime_R.csv")
# split data into year 0 and year + 10 
dim(df)
names(df)
head(df,2)
tail(df,2)

df0 <- df %>%
  select(-ends_with('10'))
df10 <- df %>%
  select(ends_with('10'))

#str(df)
```

```{r}
df1 <- df[,c("Southern","Males")]
df2 <- df[,c("Southern","Males10")]
df2$Southern <- ifelse(df2$Southern == 0, 3,4)
names(df2)[2] <- "Males"

df_stack <- rbind(df1,df2)
df_stack$Southern <- as.factor(df_stack$Southern)

aov_test <- aov(Males ~ Southern, data=df_stack)
summary(aov_test)

hist(aov_test$residuals)
qqPlot(aov_test$residuals)

kruskal.test(Males ~ Southern, data = df_stack)

ggbetweenstats(
  data = df_stack,
  x = "Southern",
  y = "Males",
  type = "nonparametric", # ANOVA or Kruskal-Wallis
  plot.type = "box",
  pairwise.comparisons = TRUE,
  pairwise.display = "significant",
  centrality.plotting = FALSE,
  bf.message = FALSE
)

```

```{r}
lm.fit <- lm(CrimeRate ~ ExpenditureYear0, data=df0)
summary(lm.fit)

plot(df0$CrimeRate, df$ExpenditureYear0)
abline(lm.fit, lwd=3, col="red")

par(mfrow = c(2,2))
plot(lm.fit)

```




```{r}
model <- lm(CrimeRate~.,data=df0)
summary(model)

lm.fit <- lm(
  CrimeRate ~ 
    Education + Youth + Wage + BelowWage 
    + ExpenditureYear0, data=df0)

lm.fit2 <- lm(
  CrimeRate ~
    Youth + Wage + BelowWage
    + ExpenditureYear0, data=df0
)

summary(lm.fit)
summary(lm.fit2)

anova(lm.fit, lm.fit2)


```


```{r}
lm.fit3 <- lm(
  CrimeRate ~ 
    + log10(Youth)
    + log10(Wage)
    + log10(BelowWage) 
    + log10(ExpenditureYear0), data=df0
)

lm.fit4 <- lm(
  CrimeRate ~ 
  + log10(Youth)
  + log10(BelowWage) 
  + log10(ExpenditureYear0), data=df0
)

summary(lm.fit3)
summary(lm.fit4)

anova(lm.fit3, lm.fit4)


```



